- alias: Leak Notifier
  description: ''
  trigger:
  - entity_id:
    - sensor.brady_leak
    - sensor.brees_leak
    from: dry
    platform: state
  condition: []
  action:
  - data_template:
      message: 'Detector {{trigger.to_state.name.split(''.'')[0]}} is reporting {{trigger.to_state.state}}!'
      title: 'Leak sensor: {{trigger.to_state.state}}'
    service: notify.mobile_app_zphone
- alias: Bootup Initializers
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
    - data:
        payload: ping
        qos: 1
        topic: /reinitialize
      service: mqtt.publish
    - service: cloud.remote_connect
- alias: Filter Replacement Alert
  description: 'Sends notifications when the scheduled filter replacement date is greater than now'
  trigger: 
    - platform: time_pattern
      seconds: '00'
      minutes: '30'
  condition: 
    condition: and
    conditions: 
      - condition: state
        entity_id: person.zachary_stone
        state: home
      - condition: time
        after: '11:00:00'
        before: '21:00:00'
      - condition: template
        value_template: "{{(now().timestamp() | int) > (state_attr('input_datetime.filter_replacement','timestamp') | int)}}"
  action: 
  - service: notify.mobile_app_zphone
    data:
      title: 'Filter needs to be replaced'
      message: 'Fix it now, or punt?'
      data: 
        actions:
        - action: "filter.punt" 
          title: "Punt" 
        - action: "filter.replace" 
          title: "Replace"  
- alias: Handle Filter Punt
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: filter.punt
  action:
    - service:  script.filter_replacement_punt

- alias: Handle Filter Replace
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: filter.replace
  action:
    - service: script.filter_replacement_now
  
