- id: ccbd6ca549f34922abd2fe3892f234d1
  alias: Leak Notifier
  description: ''
  trigger:
  - entity_id:
    - sensor.brady_leak
    - sensor.brees_leak
    from: dry
    platform: state
  condition: []
  action:
  - data_template:
      message: 'Detector {{trigger.to_state.name.split(''.'')[0]}} is reporting {{trigger.to_state.state}}!'
      title: 'Leak sensor: {{trigger.to_state.state}}'
    service: notify.mobile_app_zphone
- id: '1590891887225'
  alias: Reinitialize Sensors
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      payload: ping
      qos: 1
      topic: /reinitialize
    service: mqtt.publish
- alias: Filter Replacement Alert
  description: 'Sends notifications when the scheduled filter replacement date is greater than now'
  trigger: 
    - platform: time_pattern
      seconds: '/3'
  condition: 
    condition: and
    conditions: 
      - condition: state
        entity_id: person.zachary_stone
        state: home
      - condition: time
        after: '11:00:00'
        before: '21:00:00'
      - condition: template
        value_template: '{{(to_timestamp(trigger.now) | Int) > (state_attr("input_datetime.filter_replacement", "timestamp") | Int) }}'
  action: 
  - service: notify.mobile_app_zphone
    data:
      title: 'Filter needs to be replaced'
      message: 'Fix it now, or punt?'
      data: 
        actions:
        - action: "filter" 
          title: "Punt" 
        - action: "filter" 
          title: "Replace"  
- alias: Handle Filter Event
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: filter
  action:
    - service: script.extend_filter_replacement
      data_template:
        days: 2 
