- id: '1590801703221'
  alias: Test Wet
  description: ''
  trigger:
  - payload: wet
    platform: mqtt
    topic: home/test/water
  condition: []
  action:
  - device_id: 54f2445bb86b4dd9b0145ee095cd8cb4
    domain: switch
    entity_id: switch.bedroom_lamp
    type: turn_off
  - data:
      message: hello
    service: notify.mobile_app_sm_g975u
- id: '1590864795344'
  alias: brady-unavailable
  description: ''
  trigger:
  - entity_id: sensor.brady_ping
    platform: state
    to: unknown
  condition: []
  action:
  - data:
      message: brady is unavailable
    service: notify.mobile_app_sm_g975u
  - data_template:
      entity_id: sensor.brady_leak
      state: unknown
    service: python_script.set_state
