- id: c299d2ad88b341a0974bd85ed41d12bd
  alias: Leak Unavailable
  description: ''
  trigger:
  - entity_id:
    - sensor.disposal_leak
    - sensor.dishwasher_leak
    - sensor.washing_machine_leak
    - sensor.condensation_pump_leak
    for: 00:00:30
    platform: state
    to: unavailable
  condition: []
  action:
  - data_template:
      message: Detector {{trigger.to_state.name.split('.')[0]}} is reporting {{trigger.to_state.state}}!
      title: Leak sensor unavailable
    service: notify.mobile_app_zphone
- id: c26cbb64880a44919e67ee97393156bf
  alias: Bootup Initializers
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      payload: ping
      qos: 1
      topic: /reinitialize
    service: mqtt.publish
- alias: Filter Replacement Alert
  description: Sends notifications when the scheduled filter replacement date is greater
    than now
  trigger:
  - platform: time_pattern
    seconds: '00'
    minutes: '30'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: person.zachary_stone
      state: home
    - condition: time
      after: '11:00:00'
      before: '21:00:00'
    - condition: template
      value_template: '{{(now().timestamp() | int) > (state_attr(''input_datetime.filter_replacement'',''timestamp'')
        | int)}}'
  action:
  - service: notify.mobile_app_zphone
    data:
      title: Filter needs to be replaced
      message: Fix it now, or punt?
      data:
        actions:
        - action: filter.punt
          title: Punt
        - action: filter.replace
          title: Replace
  id: 99926e7ec23b455d9213e41549ddd02b
- alias: Handle Filter Punt
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: filter.punt
  action:
  - service: script.filter_replacement_punt
  id: 86c5116675024516990133c5fc938c7d
- alias: Handle Filter Replace
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: filter.replace
  action:
  - service: script.filter_replacement_now
  id: 8817ea4069d44c18bc88ea0aaacf5bd3
- id: '1591232432136'
  alias: Bedroom Light Motion
  description: ''
  trigger:
  - payload: detected
    platform: mqtt
    topic: /home/wilson/pir
  condition:
  - condition: template
    value_template: '{{ state_attr("sun.sun", "elevation") < 12 }}'
  - condition: state
    entity_id: input_boolean.bedtime
    state: 'off'
  action:
  - device_id: 54f2445bb86b4dd9b0145ee095cd8cb4
    domain: switch
    entity_id: switch.bedroom_lamp
    type: turn_on
- id: '1591453666780'
  alias: Router Connectivity Failure
  description: ''
  trigger:
  - entity_id: binary_sensor.local
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Lost Connection to local router
      name: Connection Lost
    entity_id: binary_sensor.local
    service: logbook.log
- id: '1593294703590'
  alias: Leak Detected
  description: ''
  trigger:
  - entity_id:
    - sensor.disposal_leak
    - sensor.dishwasher_leak
    - sensor.washing_machine_leak
    - sensor.condensation_pump_leak
    platform: state
    to: wet
  condition: []
  action:
  - data_template:
      message: Detector {{trigger.to_state.name.split('.')[0]}} is reporting {{trigger.to_state.state}}!
      title: Leak Detected!
    service: notify.mobile_app_zphone
- id: '1593310193877'
  alias: Set Bedtime
  description: Sets the bedtime flag automatically at night when I've gone to bed
  trigger:
  - entity_id: sensor.zphone_battery_state
    for: 00:30:00
    platform: state
    to: charging
  - entity_id: sensor.zphone_battery_state
    for: '"00:30:00"'
    platform: state
    to: Full
  condition:
  - after: '22:00'
    before: 06:00
    condition: time
  - condition: device
    device_id: 54f2445bb86b4dd9b0145ee095cd8cb4
    domain: switch
    entity_id: switch.bedroom_lamp
    for:
      hours: 0
      minutes: 0
      seconds: 0
    type: is_off
  action:
  - data: {}
    entity_id: input_boolean.bedtime
    service: input_boolean.turn_on
- id: '1593312256950'
  alias: bedtime scene
  description: ''
  trigger:
  - entity_id: input_boolean.bedtime
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - scene: scene.bedtime
