- id: c299d2ad88b341a0974bd85ed41d12bd
  alias: Leak Unavailable
  description: ''
  trigger:
  - entity_id:
    - sensor.disposal_leak
    - sensor.dishwasher_leak
    - sensor.washing_machine_leak
    - sensor.condensation_pump_leak
    for: 00:00:30
    platform: state
    to: unavailable
  condition: []
  action:
  - data_template:
      message: Detector {{trigger.to_state.name.split('.')[0]}} is reporting {{trigger.to_state.state}}!
      title: Leak sensor unavailable
    service: notify.mobile_app_zphone
- id: c26cbb64880a44919e67ee97393156bf
  alias: Bootup Initializers
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      payload: ping
      qos: 1
      topic: /reinitialize
    service: mqtt.publish
- alias: Filter Replacement Alert
  description: Sends notifications when the scheduled filter replacement date is greater
    than now
  trigger:
  - platform: time_pattern
    seconds: '00'
    minutes: '30'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: person.zachary_stone
      state: home
    - condition: time
      after: '11:00:00'
      before: '21:00:00'
    - condition: template
      value_template: '{{(now().timestamp() | int) > (state_attr(''input_datetime.filter_replacement'',''timestamp'')
        | int)}}'
  action:
  - service: notify.mobile_app_zphone
    data:
      title: Filter needs to be replaced
      message: Fix it now, or punt?
      data:
        actions:
        - action: filter.punt
          title: Punt
        - action: filter.replace
          title: Replace
  id: 99926e7ec23b455d9213e41549ddd02b
- alias: Handle Filter Punt
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: filter.punt
  action:
  - service: script.filter_replacement_punt
  id: 86c5116675024516990133c5fc938c7d
- alias: Handle Filter Replace
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: filter.replace
  action:
  - service: script.filter_replacement_now
  id: 8817ea4069d44c18bc88ea0aaacf5bd3
- id: '1591232432136'
  alias: Bedroom Light Motion
  description: ''
  trigger:
  - payload: detected
    platform: mqtt
    topic: /home/wilson/pir
  - platform: state
    entity_id: binary_sensor.wyzesense_77a63fb2
    to: 'on'
  condition:
  - condition: template
    value_template: '{{ state_attr("sun.sun", "elevation") < 8 }}'
  - condition: state
    entity_id: input_boolean.bedtime
    state: 'off'
  action:
  - device_id: bfaf6012d1764219ae6a3c865d7d03e6
    domain: switch
    entity_id: switch.bedroom_lamp
    type: turn_on
  - delay: 00:20:00
  - device_id: bfaf6012d1764219ae6a3c865d7d03e6
    domain: switch
    entity_id: switch.bedroom_lamp
    type: turn_off
  mode: restart
- id: '1593294703590'
  alias: Leak Detected
  description: ''
  trigger:
  - entity_id:
    - sensor.disposal_leak
    - sensor.dishwasher_leak
    - sensor.washing_machine_leak
    - sensor.condensation_pump_leak
    platform: state
    to: wet
  condition: []
  action:
  - data_template:
      message: Detector {{trigger.to_state.name.split('.')[0]}} is reporting {{trigger.to_state.state}}!
      title: Leak Detected!
    service: notify.mobile_app_zphone
- id: '1593310193877'
  alias: Set Bedtime
  description: Sets the bedtime flag automatically at night when I've gone to bed
  trigger:
  - entity_id: sensor.zphone_battery_state
    for: 00:30:00
    platform: state
    to: charging
  - entity_id: sensor.zphone_battery_state
    for: '"00:30:00"'
    platform: state
    to: Full
  condition:
  - after: '22:00'
    before: 06:00
    condition: time
  - condition: device
    device_id: 54f2445bb86b4dd9b0145ee095cd8cb4
    domain: switch
    entity_id: switch.bedroom_lamp
    for:
      hours: 0
      minutes: 0
      seconds: 0
    type: is_off
  action:
  - data: {}
    entity_id: input_boolean.bedtime
    service: input_boolean.turn_on
- id: '1593312256950'
  alias: bedtime scene
  description: ''
  trigger:
  - entity_id: input_boolean.bedtime
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - scene: scene.bedtime
  - service: climate.set_temperature
    data:
      temperature: 69
    target:
      entity_id: climate.my_ecobee
  mode: single
- id: '1593577167509'
  alias: Woken Up
  description: Turns off bedtime when I'm using my phone
  trigger:
  - entity_id: sensor.zphone_battery_state
    for: 00:05:00
    platform: state
    to: discharging
  condition:
  - after: '7:00'
    before: '17:00'
    condition: time
  action:
  - data: {}
    entity_id: input_boolean.bedtime
    service: input_boolean.turn_off
  - service: climate.set_temperature
    data:
      temperature: 70
    target:
      entity_id: climate.my_ecobee
  mode: single
- id: '1593822612999'
  alias: Evening Living Room Lights
  description: ''
  trigger:
  - entity_id: binary_sensor.wyzesense_7794df66
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.bedtime
    state: 'off'
  - condition: template
    value_template: '{{ state_attr("sun.sun", "elevation") < 8}}'
  - condition: device
    device_id: a480d205dacb4755900ad0052cdb8c31
    domain: light
    entity_id: light.living_room_lights
    type: is_off
  action:
  - brightness_pct: 75
    device_id: a480d205dacb4755900ad0052cdb8c31
    domain: light
    entity_id: light.living_room_lights
    type: turn_on
- id: '1593822911752'
  alias: Night Time Living Room Lights
  description: ''
  trigger:
  - entity_id: binary_sensor.wyzesense_7794df66
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.bedtime
    state: 'on'
  action:
  - brightness_pct: 1
    device_id: a480d205dacb4755900ad0052cdb8c31
    domain: light
    entity_id: light.living_room_lights
    type: turn_on
- id: '1594411592592'
  alias: First Floor Exhaust Shutoff
  description: Turns off the bathroom exhaust on a timer fans when the lights go off.
  trigger:
  - device_id: 88329ae2c1bc4da0a2062a973ab06aaf
    domain: switch
    entity_id: switch.first_floor_bath_light
    for:
      hours: 0
      minutes: 30
      seconds: 0
    platform: device
    type: turned_off
  condition:
  - condition: device
    device_id: 5149ce3fa0184911859a1e6d5acffca2
    domain: switch
    entity_id: switch.first_floor_bath_exhaust
    type: is_on
  action:
  - device_id: 5149ce3fa0184911859a1e6d5acffca2
    domain: switch
    entity_id: switch.first_floor_bath_exhaust
    type: turn_off
  mode: single
- id: '1594411595486'
  alias: Second Floor Exhaust Shutoff
  description: Turns off the bathroom exhaust on a timer fans when the lights go off.
  trigger:
  - device_id: 4d39381c5ba140de9144d2a5964d4339
    domain: switch
    entity_id: switch.second_floor_bath_light
    for:
      hours: 0
      minutes: 30
      seconds: 0
    platform: device
    type: turned_off
  condition:
  - condition: device
    device_id: cad92a3bab9440cf8710c378c80ad6a7
    domain: switch
    entity_id: switch.second_floor_bath_exhaust
    type: is_on
  action:
  - device_id: cad92a3bab9440cf8710c378c80ad6a7
    domain: switch
    entity_id: switch.second_floor_bath_exhaust
    type: turn_off
  mode: single
- id: '1595467684775'
  alias: Stair Closet Lights
  description: ''
  trigger:
  - entity_id: binary_sensor.wyzesense_7782fdc8
    platform: state
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.wyzesense_7782fdc8
        state: 'on'
      sequence:
      - device_id: de2cc86a02a3484ebc415317d638171c
        domain: switch
        entity_id: switch.stair_closet
        type: turn_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.wyzesense_7782fdc8
        state: 'off'
      sequence:
      - device_id: de2cc86a02a3484ebc415317d638171c
        domain: switch
        entity_id: switch.stair_closet
        type: turn_off
    default:
    - data:
        message: what
        title: no matches
      service: notify.mobile_app_zphone
  mode: single
- id: '1595468075717'
  alias: Stair Lights Walkup
  description: ''
  trigger:
  - entity_id: binary_sensor.wyzesense_77a65960
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.bedtime
    state: 'off'
  action:
  - device_id: e52bd1e231cf4b19aea6e5f4ac9ab955
    domain: switch
    entity_id: switch.stairs
    type: turn_on
  - delay: 00:05:00
  - device_id: e52bd1e231cf4b19aea6e5f4ac9ab955
    domain: switch
    entity_id: switch.stairs
    type: turn_off
  mode: restart
- id: '1595468741625'
  alias: Bedroom Closet Lights
  description: ''
  trigger:
  - entity_id: binary_sensor.wyzesense_77844f1c
    platform: state
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.wyzesense_77844f1c
        state: 'on'
      sequence:
      - device_id: 591edb6da7274531ad2714bebf325ce4
        domain: switch
        entity_id: switch.bedroom_closet
        type: turn_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.wyzesense_77844f1c
        state: 'off'
      sequence:
      - device_id: 591edb6da7274531ad2714bebf325ce4
        domain: switch
        entity_id: switch.bedroom_closet
        type: turn_off
  mode: single
- id: '1605377582508'
  alias: First Floor Bath Lights
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.wyzesense_77830aba
  condition:
  - condition: state
    entity_id: input_boolean.bedtime
    state: 'off'
  action:
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: binary_sensor.wyzesense_77830aba
          state: 'on'
      sequence:
      - type: toggle
        device_id: 88329ae2c1bc4da0a2062a973ab06aaf
        entity_id: switch.first_floor_bath_light
        domain: switch
    default: []
  mode: single
- id: '1605384862692'
  alias: Botty Door Warning
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /10
  condition:
  - condition: template
    value_template: '{{ ((as_timestamp(state_attr(''switch.schedule_1f4c04'', ''next_trigger''))
      | int) - (now().timestamp() | int))/60 <= 30}}'
  - condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.wyzesense_7782fdc8
      state: 'on'
    - condition: state
      entity_id: binary_sensor.wyzesense_77830aba
      state: 'off'
  - condition: state
    entity_id: input_boolean.disable_vacuums
    state: 'off'
  action:
  - data_template:
      message: '{% if is_state(''binary_sensor.wyzesense_77830aba'',''off'')%} Bathroom
        door is closed. {% endif %} {% if is_state(''binary_sensor.wyzesense_7782fdc8'',''on'')%}
        Closet door is open.  {% endif %}

        '
      title: Botty Door Warning
    service: notify.mobile_app_zphone
  mode: single
