
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
python_script:
sensor: !include sensors.yaml
binary_sensor:
  - platform: ping
    name: local_router_connectivity
    host: 10.0.0.1
    count: 2
    scan_interval: 2
  - platform: wyzesense
    device: auto
    #lovelace:
    #  mode: yaml
logger:
  default: info
  logs:
    custom_components.wyzesense: debug
    wyzesense.gateway: debug
