- platform: mqtt
  state_topic: /home/brady/leak
  name: brady leak
  availability_topic: /home/brady/status   
  payload_available: "online"
  payload_not_available: "offline"

- platform: mqtt
  state_topic: /home/brady/pir
  name: brady pir
  availability_topic: /home/brady/status   
  payload_available: "online"
  payload_not_available: "offline"

- platform: mqtt
  state_topic: /home/brady/climate
  name: brady temperature
  availability_topic: /home/brady/status   
  payload_available: "online"
  payload_not_available: "offline"
  value_template: "{{value_json.temperature}}"
  device_class: temperature

- platform: mqtt
  state_topic: /home/brady/climate
  name: brady humidity
  availability_topic: /home/brady/status   
  payload_available: "online"
  payload_not_available: "offline"
  value_template: "{{value_json.humidity}}"
  device_class: humidity



- platform: mqtt
  state_topic: /home/brees/leak
  name: brees leak
  availability_topic: /home/brees/status   
  payload_available: "online"
  payload_not_available: "offline"

- platform: mqtt
  state_topic: /home/brees/pir
  name: brees pir
  availability_topic: /home/brees/status   
  payload_available: "online"
  payload_not_available: "offline"

- platform: mqtt
  state_topic: /home/brees/climate
  name: brees temperature
  availability_topic: /home/brees/status   
  payload_available: "online"
  payload_not_available: "offline"
  value_template: "{{value_json.humidity}}"
  device_class: temperature

- platform: mqtt
  state_topic: /home/brees/climate
  name: brees humidity
  availability_topic: /home/brees/status   
  payload_available: "online"
  payload_not_available: "offline"
  value_template: "{{value_json.humidity}}"
  device_class: humidity
- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_use
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
