title: Home
views:
  - badges:
      - entity: person.zachary_stone
      - entity: sensor.zphone_battery_level
      - entity: sensor.zphone_battery_state
      - entity: sensor.zphone_wifi_connection
    cards:
      - entities:
          - entity: switch.bedroom_lamp
        title: Switch
        type: entities
      - entity: weather.home
        type: weather-forecast
      - entities:
          - entity: sensor.dishwasher_leak
          - entity: sensor.disposal_leak
          - entity: sensor.washing_machine_leak
        title: Leaks
        type: entities
      - entities:
          - entity: input_datetime.filter_replacement
        type: glance
      - type: entities
        title: Climate
        entities:
          - entity: sensor.kitchen_temperature
          - entity: sensor.kitchen_humidity
          - entity: sensor.office_temperature
          - entity: sensor.office_humidity
    title: Home
  - badges: []
    cards:
      - type: glance
        title: Leak Detectors
        entities: 
          - entity: sensor.dishwasher_leak
          - entity: sensor.disposal_leak
          - entity: sensor.washing_machine_leak
      - type: vertical-stack
        title: HVAC FIlter
        cards:
          - type: markdown
            title: Days Until Replacement
            content: |-
                <font size="6"> <center> {{(((state_attr(
                   'input_datetime.filter_replacement',
                   'timestamp') | int) - 
                (now().timestamp() | int))
                /60/60/24) | int }}
                </center> </font>
            style:
              text-align: center
          - type: glance
            entities: 
              - entity: input_datetime.filter_replacement
            show_name: false

          - type: horizontal-stack
            cards: 
            - type: button
              icon: 'mdi:update'
              name: Replace Now
              tap_action: 
                action: call-service
                service: script.filter_replacement_now
              icon_height: 20px
            - type: button
              icon: 'mdi:football'
              name: Punt
              tap_action: 
                action: call-service
                service: script.filter_replacement_punt
              icon_height: 20px
    panel: false
    path: home-maintenence
    title: Maintenance
  - badges: 
    title: Server Status
    cards: 
      - type: custom:vertical-stack-in-card
        cards:
          - type: entities
            title: Server Pi
            show_header_toggle: false
            entities:
              - entity: sensor.last_boot
                name: Last boot
                icon: mdi:clock
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                entities:
                  - entity: sensor.processor_use
                    name: CPU
                points_per_hour: 60
                hours_to_show: 2
                icon: mdi:memory
                show:
                  labels: true
                  extrema: true                
                color_thresholds:
                  - value: 0
                    color: '#40bf40'
                  - value: 10
                    color: '#ffde00'
                  - value: 50
                    color: '#bf4040'
              - type: custom:mini-graph-card
                entities:
                  - entity: sensor.cpu_temperature
                    name: CPU Temperature
                points_per_hour: 60
                hours_to_show: 2
                decimals: 0
                show:
                  labels: true
                  extrema: true 
                color_thresholds:
                  - value: 0
                    color: '#cccccc'
                  - value: 45
                    color: '#ffde00'
                  - value: 65
                    color: '#bf4040'

          - type: custom:multiple-entity-row
            name: RPi I/O
            show_state: false
            icon: mdi:router-wireless
            entity: sensor.network_in_eth0
            entities:
              - entity: sensor.network_in_eth0
                name: Kbyte Received
              - entity: sensor.network_out_eth0
                name: Kbyte Sent
              
          - type: custom:bar-card
            entities:
              - entity: sensor.disk_use_percent_home
                icon: mdi:harddisk
                title: HDD
                severity:
                - value: 50
                  color: '#40bf40'
                - value: 80
                  color: '#ffde00'
                - value: 100
                  color: '#bf4040'
              - entity: sensor.memory_use_percent
                icon: mdi:memory
                title: RAM
                severity:
                - value: 20
                  color: '#40bf40'
                - value: 50
                  color: 'var(--primary-color)'
                - value: 100
                  color: '#bf4040'
            height: 40px
            columns: 1
            entity_config: true
            show_icon: true
            title_position: inside
            # title_position: 'off'
            align: split
            rounding: 5px
            padding: 5px
            background_style:
              background: "#000"
              opacity: 0.05
            icon_style:
              height: 34px
              width: 34px
              filter: "none"
            value_style:
              text-shadow: "none"
              font-size: "18px"
              font-weight: "normal"
              color: "var(--primary-text-color)"
            title_style:
              text-shadow: "none"
              color: "var(--primary-text-color)"
              # color: "#fff"
              font-weight: "normal"
resources:
  - type: module
    url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
  - type: module 
    url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
  - type: module
    url: /hacsfiles/bar-card/bar-card.js
  - type: module 
    url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
